### PR TITLE
Coerce float type in Float type

### PR DESCRIPTION
**Pull request by radeklos**
When `source_value` is not float the original data type is returned (int, decimal, ..). `Float.serialize_value` coerce all values to be floats.

### CODE REVIEW

**Comment by radeklos** [comment]
@mikeywaites where and how do you want to bump the version number?

**Comment by mikeywaites** [comment]
https://github.com/mikeywaites/kim/blob/master/VERSION

Simply update the minor version number here please @radeklos 

Apprecaited. :+1:

**Comment by radeklos** [comment]
@mikeywaites Minor? This is patch. I would change the version from `0.1.9` to `0.1.10`.

**Comment by osldev** [comment]
Apologies that is in fact what I meant.

On 10 June 2015 at 15:30, radeklos <notifications@github.com> wrote:

> @mikeywaites <https://github.com/mikeywaites> Minor? This is patch. I
> would change the version from 0.1.9 to 0.1.10.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeywaites/kim/pull/47#issuecomment-110774761>.
>



-- 
*Mike Waites*
Lead Developer

Old St Labs
Enterprise Level Innovation

6th Floor,
22 Upper Ground
London, SE1 9PD,
United Kingdom

M: (+44)7967168590
E: mike@oldstlabs.com

www.oldstlabs.com
<http://s.wisestamp.com/links?url=http%3A%2F%2Fs.wisestamp.com%2Flinks%3Furl%3Dhttp%253A%252F%252Fwww.oldstlabs.com%252F%26amp%3Bsn%3D&sn=>

[image: Twitter]
<http://s.wisestamp.com/links?url=https%3A%2F%2Ftwitter.com%2FOldStLabs&sn=>
 [image: LinkedIn]
<http://s.wisestamp.com/links?url=https%3A%2F%2Fwww.linkedin.com%2Fcompany%2Fold-st-labs&sn=>

**Comment by mikeywaites** [comment]
Thanks @radeklos

**Pull request merged**
